plugins {
    id 'java'
}

group = 'com.flyaway.skipper'
version = '1.4.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven { url = 'https://repo.essentialsx.net/releases/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.3.build.159-beta'
    compileOnly 'net.essentialsx:EssentialsX:2.21.2'
}

tasks.jar {
    archiveBaseName.set("NightSkipper")
}

tasks.processResources {
    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                name: project.name,
                group: project.group
        )
    }
}
