name: ${name}
version: ${version}
main: ${group}.${name}
api-version: 1.21
description: Пропускает ночь, когда спит нужный % игроков
author: FlyAwayMaking
website: https://github.com/flyawaymaking
depend: [Essentials]

commands:
  nskipper:
    description: Команды NightSkipper
    usage: /<command> reload

permissions:
  nskipper.admin:
    description: Позволяет использовать команду /nskipper reload
    default: op
